"""initial schema

Revision ID: dff337e274e7
Revises: 
Create Date: 2026-08-22 21:41:54.914390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dff337e274e7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Enum('admin', 'dept_admin', 'subject_lead', 'teacher', 'student', 'parent', name='accountrole', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=2000), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('answer', sa.String(length=1000), nullable=False),
    sa.Column('analysis', sa.String(length=2000), nullable=False),
    sa.Column('knowledge_points', sa.String(length=500), nullable=False),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', 'competition', name='difficulty', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source', sa.Enum('ai', 'manual', 'practice', 'ocr', name='questionsource', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('audit_status', sa.Enum('passed', 'warning', 'blocked', name='auditstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('audit_report', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('current_semester', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upload_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'previewing', 'ready', 'importing', 'imported', 'grading', 'graded', 'done', 'discarded', 'error', name='uploadsessionstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('degraded', sa.Boolean(), nullable=False),
    sa.Column('fallback_used', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ocr_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'done', 'failed', name='ocrtaskstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['upload_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parent_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.Enum('report', 'warning', 'message', name='notificationtype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.String(length=2000), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['parent.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='teacherstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('sub_role', sa.Enum('admin', 'dept_admin', 'subject_lead', 'teacher', name='teachersubrole', native_enum=False, create_constraint=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('head_teacher', sa.String(length=50), nullable=False),
    sa.Column('student_count', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['grade.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('exam_type', sa.Enum('exam', 'practice', 'homework', name='examtype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('attendee_count', sa.Integer(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('barrier_profile', sa.JSON(), nullable=False),
    sa.Column('learning_plan', sa.JSON(), nullable=False),
    sa.Column('bind_code', sa.String(length=6), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('review_level', sa.Enum('level1', 'level2', 'level3', 'level4', 'level5', 'level6', name='reviewlevel', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'archived', name='reviewtaskstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.String(length=2000), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('barrier_type', sa.Enum('concept', 'reading', 'expression', name='barriertype', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('consecutive_errors', sa.Integer(), nullable=False),
    sa.Column('consecutive_correct', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exam_record.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_parent_binding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('bind_code', sa.String(length=6), nullable=False),
    sa.Column('relation', sa.Enum('father', 'mother', 'guardian', name='parentbindingrelation', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('active', 'pending', 'inactive', name='parentbindingstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['parent.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'student_id', name='uq_binding_parent_student')
    )
    op.create_table('student_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('answer_list', sa.JSON(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exam_record.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['upload_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_task_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['review_task_id'], ['review_task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # 热 FK 列索引（D10）：SQLite 不自动为外键建索引，空表建索引零成本
    op.create_index('ix_student_class_id', 'student', ['class_id'], unique=False)
    op.create_index('ix_student_answer_student_id', 'student_answer', ['student_id'], unique=False)
    op.create_index('ix_student_answer_question_id', 'student_answer', ['question_id'], unique=False)
    op.create_index('ix_student_answer_exam_id', 'student_answer', ['exam_id'], unique=False)
    op.create_index('ix_review_task_student_id', 'review_task', ['student_id'], unique=False)
    op.create_index('ix_ocr_task_session_id', 'ocr_task', ['session_id'], unique=False)
    op.create_index('ix_student_submission_exam_id', 'student_submission', ['exam_id'], unique=False)
    op.create_index('ix_student_parent_binding_parent_id', 'student_parent_binding', ['parent_id'], unique=False)
    op.create_index('ix_student_parent_binding_student_id', 'student_parent_binding', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_student_parent_binding_student_id', table_name='student_parent_binding')
    op.drop_index('ix_student_parent_binding_parent_id', table_name='student_parent_binding')
    op.drop_index('ix_student_submission_exam_id', table_name='student_submission')
    op.drop_index('ix_ocr_task_session_id', table_name='ocr_task')
    op.drop_index('ix_review_task_student_id', table_name='review_task')
    op.drop_index('ix_student_answer_exam_id', table_name='student_answer')
    op.drop_index('ix_student_answer_question_id', table_name='student_answer')
    op.drop_index('ix_student_answer_student_id', table_name='student_answer')
    op.drop_index('ix_student_class_id', table_name='student')
    op.drop_table('review_history')
    op.drop_table('student_submission')
    op.drop_table('student_parent_binding')
    op.drop_table('student_answer')
    op.drop_table('review_task')
    op.drop_table('student')
    op.drop_table('exam_record')
    op.drop_table('class')
    op.drop_table('teacher')
    op.drop_table('parent_notification')
    op.drop_table('ocr_task')
    op.drop_table('grade')
    op.drop_table('upload_session')
    op.drop_table('school')
    op.drop_table('question')
    op.drop_table('parent')
    op.drop_table('account')
    # ### end Alembic commands ###
